project:
  type: website

website:
  site-url: "https://epiverse-trace.github.io"
  favicon: hexlogo.png
  title: "Epiverse-TRACE: tools for outbreak analytics"
  description: "A place for Epiverse-TRACE to share their reflections, learnings, and showcase available tools."
  navbar:
    left:
      - text: News
        menu:
          - text: Blog
            href: blog.qmd
          - text: Blog - Articles
            href: blog.qmd#category=R
          - text: Blog - Release notes
            href: blog.qmd#category=new-release
          - text: Presentations
            href: presentations.qmd
      - text: Use
        menu:
        - href: getting-started.qmd
        - text: Software
          href: https://epiverse-trace.r-universe.dev/packages
      - text: Learn
        menu:
          - text: Learning materials
            href: learn.qmd
          - href: resources.qmd
      - text: Contribute
        menu:
          - text: "Good first issues"
            href: "https://github.com/search?q=org%3Aepiverse-trace++label%3A%22good+first+issue%22+is%3Aopen&type=issues"
          - text: Get involved
            href: get-involved.qmd
      - text: About
        href: people.qmd
    tools:
      - icon: github
        href: https://github.com/epiverse-trace
      - icon: twitter
        href: https://twitter.com/Epiverse_TRACE
  google-analytics: "G-XZ471458FQ"
  twitter-card:
    creator: "@Epiverse_TRACE"
  open-graph: true
  comments:
    giscus:
      repo: epiverse-trace/epiverse-trace.github.io
      repo-id: R_kgDOIcolPw
      category: "Blog post discussion"
      category-id: "DIC_kwDOIcolP84CWOm8"
      mapping: title
      reactions-enabled: true
      loading: lazy
format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css

execute:
  freeze: auto
