name: alex
on:
  pull_request:
    branches: main

jobs:
  alex:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-alex@ee2bd61307cf0eb11f6ce460d58352e10bf4b8b7
        with:
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning
